### ISSUE TITLE
Not finding window

### ISSUE THREAD

**Issue by BasselKhaled24** [JU5TDIE/Lester-Ver2.0#8] opened 2024-10-29 02:40 UTC
Hi, first of all thanks for making this program. I am trying to run the program but it gets stuck trying to find a window in the check_window function (line 25) and it goes into an infinite loop. Any ideas why this is happening? All the requirements are downloaded and I am not getting any errors.

**Comment by JU5TDIE** [comment] 2024-10-29 15:19
Possible duplicate of https://github.com/JU5TDIE/Lester-Ver2.0/issues/4

Check this comment https://github.com/JU5TDIE/Lester-Ver2.0/issues/4#issuecomment-1865121040

**Closed as not planned** 2024-11-08 01:06 UTC
